backend:
  name: github
  repo: WaHackers-SOC-Arcade/nyumbacheck.co # <--- CHANGE THIS to your actual username and repo name
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "properties"
    label: "Properties"
    folder: "content/properties"
    create: true
    slug: "{{slug}}"
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "City", name: "city", widget: "select", options: ["Dar es Salaam", "Zanzibar", "Arusha", "Dodoma"]}
        - {label: "Neighborhood", name: "neighborhood", widget: "string"}
        - {label: "Price Amount", name: "price", widget: "number"}
        - {label: "Currency", name: "currency", widget: "select", options: ["TZS", "USD"]}
        - {label: "Listing Type", name: "type", widget: "select", options: ["Rent", "Sale"]}
        - {label: "Status", name: "status", widget: "select", options: ["Pending", "Verified"]}
        - {label: "Photos", name: "photos", widget: "image"}
        - {label: "Title Deed", name: "deed", widget: "file"}
        - {label: "Body", name: "body", widget: "markdown"}
